title : David Ketcheson
tagline: Numerical analysis and nonlinear waves
author :
  name : David I. Ketcheson
  email : dketch@gmail.com

permalink: /:year/:month/:day/:title.html
redirects: yes
exclude: [ _posts/source/, _posts/_private/ ]

markdown: pandoc
pandoc:
   extensions: [smart, mathjax]

pygments: True
source: .
lsi: True
safe: False

#markdown: redcarpet
#redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
