title : David Ketcheson
tagline: Numerical analysis and nonlinear waves
author :
  name : David I. Ketcheson
  email : dketch@gmail.com

permalink: /:year/:month/:day/:title.html
redirects: yes
exclude: [ _posts/source/, _posts/_private/ ]

markdown: pandoc
pandoc:
   extensions: [smart, mathjax]

auto: True
pygments: True
source: .

#markdown: redcarpet2
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
